/// <reference path="../scripts/typings/jquery/jquery.d.ts" />
/// <reference path="../scripts/typings/angularjs/angular.d.ts" />
/// <reference path="../scripts/typings/angularjs/angular-route.d.ts" />
/// <reference path="../scripts/typings/angularjs/angular-animate.d.ts" />
/// <reference path="../scripts/typings/angular-ui-router/angular-ui-router.d.ts" />
/// <reference path="../scripts/typings/angular-ui-bootstrap/angular-ui-bootstrap.d.ts" />
/// <reference path="../scripts/typings/xrm/xrm-2015.d.ts" />
/// <reference path="../scripts/typings/bootbox/bootbox.d.ts" />
/// <reference path="../scripts/typings/q/q.d.ts" />
//# sourceMappingURL=_app.js.map